---
title: "PM566-lab-12"
author: "Carissa Feliciano"
output:
  html_document:
    toc: TRUE
    toc_float: TRUE
---

```{r setup, message=FALSE, echo=FALSE, warning=FALSE}
library(data.table)
library(tidyverse)
library(dplyr)
library(plotly)
library(DT)
library(knitr)
```

```{r}
# Initialize code chunk options
opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  eval=TRUE,
  echo = TRUE,
  cache = FALSE,
  fig.width = 7, 
  fig.align = 'center',
  fig.asp = 0.618,
  out.width = "700px")
```

```{r load-data, echo=FALSE}
source("process_COVID_data.R")
```

```{r}
source("process_COVID_data.R")
p1_scatter <- cv_states_today|> 
  plot_ly(x = ~pop_density, y = ~deathsper100k,
          type = 'scatter', mode = 'markers', color = ~state,
          size = ~population, sizes = c(5, 70), marker = list(sizemode='diameter', opacity=0.5),
          hoverinfo = 'text',
          text = ~paste( paste(state, ":", sep=""), paste(" Cases per 100k: ", per100k, sep="") , paste(" Deaths per 100k: ",
                        deathsper100k, sep=""), sep = "<br>")) |>
  layout(title = "Population-normalized COVID-19 deaths vs. population density",
                  yaxis = list(title = "Deaths per 100k"), xaxis = list(title = "Population Density"),
         hovermode = "compare")

# filter out "District of Columbia"
cv_states_today_scatter <- cv_states_today |> filter(state!="District of Columbia")

p2_scatter <- cv_states_today_scatter |> 
  plot_ly(x = ~pop_density, y = ~deathsper100k,
          type = 'scatter', mode = 'markers', color = ~state,
          size = ~population, sizes = c(5, 70), marker = list(sizemode='diameter', opacity=0.5),
          hoverinfo = 'text',
          text = ~paste( paste(state, ":", sep=""), paste(" Cases per 100k: ", per100k, sep="") , paste(" Deaths per 100k: ",
                        deathsper100k, sep=""), sep = "<br>")) |>
  layout(title = "Population-normalized COVID-19 deaths vs. population density",
                  yaxis = list(title = "Deaths per 100k"), xaxis = list(title = "Population Density"),
         hovermode = "compare")
```

```{r}
cv_states_today_filter <- cv_states_today |> filter(state!="District of Columbia")

p3_scatter <- cv_states_today_filter |>
  plot_ly(x = ~pop_density, y = ~per100k, 
          type = 'scatter', 
          mode = 'markers', 
          color = ~state,
          size = ~population, sizes = c(5, 70), marker = list(sizemode='diameter', opacity=0.5),
          hoverinfo = 'text',
          text = ~paste( paste(state, ":", sep=""),
                         paste(" Cases per 100k: ", per100k, sep=""),
                         paste(" Deaths per 100k: ", deathsper100k, sep=""),
                         sep = "<br>")) |>
  layout(title = "Population-normalized COVID-19 deaths (per 100k) vs. Population density for US States",
         yaxis = list(title = "Cases per 100k"),
         xaxis = list(title = "Population Density"),
         hovermode = "compare")
```

```{r}
# filter out "District of Columbia"
p4_scatter <- cv_states_today_filter |>
  plot_ly(x = ~pop_density, y = ~deaths, 
          type = 'scatter', 
          mode = 'markers', 
          color = ~state,
          size = ~population, sizes = c(5, 70), marker = list(sizemode='diameter', opacity=0.5))
```

## Showcasing plots  {.tabset}

### Tab 1

```{r, echo=FALSE}
p1_scatter
```

### Tab 2

```{r, echo=FALSE}
p2_scatter
```

### Tab 3

```{r, echo=FALSE}
p3_scatter
```

### Tab 4

```{r, echo=FALSE}
p4_scatter
```

## {-}
